name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint
      continue-on-error: true

    - name: Run tests
      run: npm test

    - name: Tests success message
      if: success()
      run: echo "Tests passed successfully!"

    - name: Tests failure message
      if: failure()
      run: echo "Tests failed. Please check the logs for more details."
