name: Code Review

on:
  push:
    branches: [ master ]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      uses: actions-eslint/eslint@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run CodeQL
      uses: github/codeql-action/analyze@v1

    - name: Run SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run Review
      run: echo "Code under Review"
