name: Code Review

on: [push]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Review
      run: echo "Code under Review"

    # - name: Run Code Climate
    #   uses: paambaati/codeclimate-action@v2.7.5
    #   env:
    #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    # - name: Run CodeQL
    #   uses: github/codeql-action/analyze@v1
