name: Custom

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Generate release notes
      id: release_notes
      run: |
        echo "::set-output name=notes::$(node generate-release-notes.js)"

    - name: Create Release Notes
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo } = context.repo
          const release = context.payload.release
          const notes = `${release.body}\n\n${steps.release_notes.outputs.notes}`
          github.repos.updateRelease({ owner, repo, release_id: release.id, body: notes })
