name: Dependency updates

on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true

    - name: Install dependencies
      run: npm install

    - name: Check for outdated dependencies
      run: npm outdated

    - name: Update dependencies
      run: npm update

    - name: Run tests
      run: npm test
    - name: Update Status
      run: echo "All dependencies have been updated!"
    # - name: Commit and push if it was updated
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add -A
    #     git diff --quiet && git diff --staged --quiet || git commit -m "Update dependencies"
    #     git push
