name: Deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 
      with:
        heroku_api_key: "apiKey" # I used a dummy key and app name as heroku requires payment information
        heroku_app_name: "deployed-app-name" 
        heroku_email: "malaikazafar2003@gmail.com"
    
    - name: Success
      run: echo "Deployment Successful"
   
