name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run task
      run: npm run task

    - name: Task success message
      run: echo "Task completed successfully!"

    - name: Notify on success
      uses: actions/github-script@v3
      with:
        script: |
          const issue = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Scheduled task completed successfully',
            body: 'The scheduled task completed successfully at ' + new Date().toISOString()
          }
          github.issues.create(issue)
